const geradorRemessaCaixa = require('./bancos/caixa/index')
const PATH = require(`path`);

module.exports.gerarRemessaCaixa = function (
  loteServico,
  sequenciaLoteServico,
  tipoInscricao,
  numeroInscricao,
  Agencia,
  AgenciaDV,
  CodigoCedente,
  nomeEmpresa,
  codigoRemessaRetorno,
  dataGeracao,
  horaGeracao,
  NSA,
  tipoRemessa, //1-> REMESSA-TESTE, 2-> REMESSA-PRODUÇÃO
  tipoOperacao, //R -> Remesssa, T -> Retorno
  codigoConvenio,
  mensagem1,
  mensagem2,
  numRemessaRetornoNSA,
  dataGravacaoRemessaRetorno,
  dataCredito,
  codigoMovimentoRemessa,
  modalidadeCarteira,
  nossoNumero, //CCNNNNNNNNNNNNNNN
  codigoCarteira,
  formaDeCadastroTituloNoBanco,
  tipoDocumento,
  identificacaoEmisssaoBloqueto,
  identificacaoEntregaBloqueto,
  numeroDocumentoDeCobracao,
  dataVencimentoTitulo,
  valorTitulo,
  agenciaEncarregadaCobranca,
  agenciaDVEncarregadaCobranca,
  especieTitulo,
  identificaoTituloAceitacao,
  dataEmissaoTitulo,
  codigoJurosDeMora,
  dataJurosDeMora,
  juroDeMoraPorDiaTaxa,
  codigoDesconto1,
  dataDesconto1,
  valorPercentualDescontoConcedido,
  valorIOFRecolhido,
  valorAbatimento,
  identificacaoTituloEmpresa,
  codigoParaProtesto,
  numeroDeDiasParaProtesto,
  codigoParaBaixa_Devolucao,
  numeroDeDiasBaixa_Devolucao,
  tipoInscricaoSacado,
  numeroInscricaoSacado,
  nomeSacado,
  enderecoSacado,
  bairroSacado,
  cepSacado,
  sufixoCEPSacado,
  CidadeSacado,
  ufSacado,
  tipoInscricao_Sacador_Avalista,
  numeroInscricao_Sacador_Avalista,
  nomeSacador_Sacador_Avalista,
  nossoNumeroBancoCorrespondente,
  filepath
) {
  // const filepath = PATH.resolve(__dirname, 'uploads', `${new Date().getTime()}.REM`)
  // const filepath = PATH.resolve(__dirname, 'uploads')
  try {
    const response = geradorRemessaCaixa.gerarRemessa(loteServico,
      sequenciaLoteServico,
      tipoInscricao,
      numeroInscricao,
      Agencia,
      AgenciaDV,
      CodigoCedente,
      nomeEmpresa,
      codigoRemessaRetorno,
      dataGeracao,
      horaGeracao,
      NSA,
      tipoRemessa, //1-> REMESSA-TESTE, 2-> REMESSA-PRODUÇÃO
      tipoOperacao, //R -> Remesssa, T -> Retorno
      codigoConvenio,
      mensagem1,
      mensagem2,
      numRemessaRetornoNSA,
      dataGravacaoRemessaRetorno,
      dataCredito,
      codigoMovimentoRemessa,
      modalidadeCarteira,
      nossoNumero, //CCNNNNNNNNNNNNNNN
      codigoCarteira,
      formaDeCadastroTituloNoBanco,
      tipoDocumento,
      identificacaoEmisssaoBloqueto,
      identificacaoEntregaBloqueto,
      numeroDocumentoDeCobracao,
      dataVencimentoTitulo,
      valorTitulo,
      agenciaEncarregadaCobranca,
      agenciaDVEncarregadaCobranca,
      especieTitulo,
      identificaoTituloAceitacao,
      dataEmissaoTitulo,
      codigoJurosDeMora,
      dataJurosDeMora,
      juroDeMoraPorDiaTaxa,
      codigoDesconto1,
      dataDesconto1,
      valorPercentualDescontoConcedido,
      valorIOFRecolhido,
      valorAbatimento,
      identificacaoTituloEmpresa,
      codigoParaProtesto,
      numeroDeDiasParaProtesto,
      codigoParaBaixa_Devolucao,
      numeroDeDiasBaixa_Devolucao,
      tipoInscricaoSacado,
      numeroInscricaoSacado,
      nomeSacado,
      enderecoSacado,
      bairroSacado,
      cepSacado,
      sufixoCEPSacado,
      CidadeSacado,
      ufSacado,
      tipoInscricao_Sacador_Avalista,
      numeroInscricao_Sacador_Avalista,
      nomeSacador_Sacador_Avalista,
      nossoNumeroBancoCorrespondente,
      filepath)
    return response;
  } catch (error) {
    console.log(error)
  }


}

